// pwa.js
// One place for everything install/offline/update related, so the entry point
// (main.jsx) only has to call initPwa() and no component has to know how the
// service worker is registered.
//
// The service worker itself is generated by vite-plugin-pwa (see vite.config.js)
// and precaches ONLY the app shell. This module owns:
//   - registering it (via the virtual module, dynamically imported so the
//     workbox-window runtime is not part of the first-paint bundle),
//   - exposing "a new version is ready" so the UI can offer an explicit refresh
//     instead of the worker seizing control mid-lesson (registerType 'prompt'),
//   - tracking online/offline so the app can say so,
//   - the INSTALL capability model (see below).
import { create } from 'zustand';

// ---------------------------------------------------------------------------
// INSTALL CAPABILITY — NATIVE PROMPT ONLY
//
// The install button is shown ONLY when the browser can install natively:
//
//   installed        running as an installed app (standalone), OR we recorded an
//                    install on this device. Hides the affordance.
//   nativePromptSupported   the browser implements beforeinstallprompt at all
//                    (Chromium family). Safari and Firefox do NOT, so they get
//                    no button — there is no native install to offer them.
//   nativePromptReady  the browser has actually handed us a deferred
//                    BeforeInstallPromptEvent, so prompt() will do something
//                    right now.
//
// Both flags are required. Support alone is not enough: Chrome fires
// beforeinstallprompt only after an engagement heuristic, so a supported browser
// can have no prompt ready yet — showing a button then would give a dead
// control. Ready alone is also insufficient as a guard (it implies support, but
// gating on both states the intent). iOS is deliberately NOT handled: Safari has
// no native install API, so per product decision an iOS user sees no button
// rather than a manual "Add to Home Screen" walkthrough.
// ---------------------------------------------------------------------------

const INSTALLED_KEY = 'ezw.pwa.installed.v1';

// Surfaces where an install offer makes sense. Deliberately NOT global: every
// game paints its own top-right chrome inside the canvas, so a floating button
// there could sit on top of it. These are the entry points a visitor lands on.
export const INSTALL_ROUTES = new Set(['/', '/teacher-onboarding']);

// True when the current pathname is an entry surface. Normalises a trailing
// slash and strips the query/hash so "/teacher-onboarding/" and
// "/teacher-onboarding?x=1" both match.
export function isInstallRoute(pathname) {
  const raw = pathname || '/';
  const path = raw.split('?')[0].split('#')[0];
  const normalised = path.length > 1 ? path.replace(/\/$/, '') : path;
  return INSTALL_ROUTES.has(normalised);
}

function readInstalledHint() {
  try {
    return window.localStorage.getItem(INSTALLED_KEY) === '1';
  } catch {
    return false;
  }
}

function writeInstalledHint(value) {
  try {
    if (value) window.localStorage.setItem(INSTALLED_KEY, '1');
    else window.localStorage.removeItem(INSTALLED_KEY);
  } catch {
    /* private mode / storage disabled — the hint is only an optimisation */
  }
}

// Running as an installed app rather than a browser tab. Two checks because
// iOS Safari predates the display-mode media query and uses navigator.standalone
// instead.
function detectStandalone() {
  if (typeof window === 'undefined') return false;
  try {
    if (window.matchMedia?.('(display-mode: standalone)').matches) return true;
    // Also true when launched from the OS app switcher on Android.
    if (window.matchMedia?.('(display-mode: fullscreen)').matches) return true;
    if (window.matchMedia?.('(display-mode: minimal-ui)').matches) return true;
  } catch {
    /* media query unsupported — fall through */
  }
  return window.navigator?.standalone === true;
}

function detectNativePromptSupported() {
  if (typeof window === 'undefined') return false;
  return 'onbeforeinstallprompt' in window;
}

// The pure decision behind low-power mode: given the raw device signals, should
// the app drop its heavy decoration? Split out from the detection so it can be
// unit-tested without a browser (see pwa.test.js).
//
// Any one signal is enough:
//   - Save-Data (the user asked to save bytes) or prefers-reduced-motion
//     (the OS asked for less motion),
//   - a low core count — the cheapest cross-browser proxy for "older phone",
//   - a low reported device memory (Chrome only).
// If the browser reports NEITHER core count nor memory it is itself old, so it
// is treated as low-power too. This only downgrades decoration; it never
// changes behaviour, layout, or access to any feature.
export function classifyLowPower({
  saveData = false,
  reducedMotion = false,
  cores = null,
  memory = null,
} = {}) {
  if (saveData || reducedMotion) return true;

  const hasCores = typeof cores === 'number' && cores > 0;
  const hasMemory = typeof memory === 'number' && memory > 0;

  if (!hasCores && !hasMemory) return true; // too old to even report → assume weak
  if (hasCores && cores <= 4) return true;
  if (hasMemory && memory <= 4) return true;
  return false;
}

// Gathers the raw signals and applies the decision above. Defaults to
// low-power when there is no browser at all (e.g. SSR/odd embeds).
function detectLowPower() {
  if (typeof window === 'undefined') return true;
  try {
    return classifyLowPower({
      saveData: Boolean(navigator.connection?.saveData),
      reducedMotion: Boolean(
        window.matchMedia?.('(prefers-reduced-motion: reduce)').matches
      ),
      cores: navigator.hardwareConcurrency ?? null,
      memory: navigator.deviceMemory ?? null, // undefined on Safari/Firefox
    });
  } catch {
    return true; // a throwing navigator is a good reason to keep it simple
  }
}

const initialOnline =
  typeof navigator === 'undefined' ? true : navigator.onLine !== false;

export const usePwaStore = create((set) => ({
  online: initialOnline,

  // --- install capability ---
  standalone: false,
  installedHint: false,
  nativePromptSupported: false,
  nativePromptReady: false, // a deferred prompt is captured and usable
  installEvent: null, // the deferred BeforeInstallPromptEvent (Chromium)

  // --- device capability ---
  lowPower: false,

  // --- update / offline readiness ---
  needRefresh: false,
  offlineReady: false,

  setOnline: (online) => set({ online }),
  setLowPower: (lowPower) => set({ lowPower }),
  setStandalone: (standalone) => set({ standalone }),
  markInstalled: () => {
    writeInstalledHint(true);
    set({ installedHint: true, nativePromptReady: false, installEvent: null });
  },
  resetInstalled: () => {
    // The browser offering install again means it is NOT installed.
    writeInstalledHint(false);
    set({ installedHint: false });
  },
  setInstalledHint: (installedHint) => set({ installedHint }),
  setNativePromptSupported: (nativePromptSupported) =>
    set({ nativePromptSupported }),
  setInstallEvent: (installEvent) =>
    set({ installEvent, nativePromptReady: Boolean(installEvent) }),
  setNeedRefresh: (needRefresh) => set({ needRefresh }),
  setOfflineReady: (offlineReady) => set({ offlineReady }),
  dismissOfflineReady: () => set({ offlineReady: false }),
}));

// The pure decision behind the install affordance. Kept separate from the hook
// so it can be unit-tested without a DOM (see pwa.test.js).
//
// Returns true only when ALL of these hold:
//   - the app is not already installed,
//   - the browser supports a native install prompt,
//   - that prompt is actually ready to fire right now.
export function shouldOfferInstall({
  standalone,
  installedHint,
  nativePromptSupported,
  nativePromptReady,
}) {
  // Already an installed app (or we recorded one on this device) → nothing.
  if (standalone || installedHint) return false;
  // No native install API (Safari, Firefox) → nothing. This is the case the
  // button must never appear for.
  if (!nativePromptSupported) return false;
  // Supported but no prompt captured yet → nothing (a dead button is worse
  // than none).
  return Boolean(nativePromptReady);
}

// Whether this device should get the light-touch decoration. Defaults to false
// so the first render on an unknown device is the safe, simple one; initPwa()
// corrects it synchronously at boot.
export function useLowPower() {
  return usePwaStore((s) => s.lowPower);
}

// The single source of truth for whether the install button renders.
export function useInstallOffer() {
  const standalone = usePwaStore((s) => s.standalone);
  const installedHint = usePwaStore((s) => s.installedHint);
  const nativePromptSupported = usePwaStore((s) => s.nativePromptSupported);
  const nativePromptReady = usePwaStore((s) => s.nativePromptReady);

  return shouldOfferInstall({
    standalone,
    installedHint,
    nativePromptSupported,
    nativePromptReady,
  });
}

// The updater returned by registerSW. Kept at module scope so applyUpdate() can
// ask the SAME registration to activate its waiting worker — calling
// registerSW() again would create a second registration.
let updateSW = null;

// Register once per page load. Safe to call repeatedly.
let initialised = false;

export function initPwa() {
  if (typeof window === 'undefined' || initialised) return;
  initialised = true;

  const store = usePwaStore.getState();

  const standalone = detectStandalone();
  // A recorded install (or an active standalone session) hides the affordance
  // even when the app is later reopened in a normal browser tab.
  const installed = standalone || readInstalledHint();
  if (standalone) writeInstalledHint(true);
  store.setStandalone(standalone);
  store.setInstalledHint(installed);
  store.setNativePromptSupported(detectNativePromptSupported());

  // Classify the device once, before first paint, and expose it as a document
  // attribute so CSS can downgrade the heavy decoration without React having to
  // thread a prop into every decorative element (see index.css).
  const lowPower = detectLowPower();
  store.setLowPower(lowPower);
  try {
    document.documentElement.dataset.lowpower = lowPower ? 'true' : 'false';
  } catch {
    /* non-fatal */
  }

  // --- online / offline -----------------------------------------------------
  // A school tablet loses wifi constantly; surfacing it explains the spinners.
  window.addEventListener('online', () => usePwaStore.getState().setOnline(true));
  window.addEventListener('offline', () => usePwaStore.getState().setOnline(false));

  // --- installed-app state can change while the page is open ---------------
  try {
    const mql = window.matchMedia('(display-mode: standalone)');
    const onChange = () => {
      const nowStandalone = mql.matches;
      usePwaStore.getState().setStandalone(nowStandalone);
      if (nowStandalone) usePwaStore.getState().markInstalled();
    };
    mql.addEventListener('change', onChange);
  } catch {
    /* older Safari: no addEventListener on MediaQueryList — ignore */
  }

  // --- install prompt (Chromium) -------------------------------------------
  window.addEventListener('beforeinstallprompt', (event) => {
    // Stop Chrome's mini-infobar so our own button is the only affordance.
    event.preventDefault();
    // Receiving this event proves the app is NOT already installed, which is a
    // more reliable signal than the stored hint — clear it.
    usePwaStore.getState().resetInstalled();
    usePwaStore.getState().setInstallEvent(event);
  });

  window.addEventListener('appinstalled', () => {
    usePwaStore.getState().setStandalone(true);
    usePwaStore.getState().markInstalled();
  });

  // Register the service worker OFF the critical path. Workbox installs a
  // worker, parses its runtime and (on update) may fetch the new shell — none of
  // which the first paint needs. Doing it in an idle callback (with a 'load'
  // floor, because a busy phone may not grant idle time) keeps it out of the
  // startup budget on exactly the slow devices that feel it most.
  scheduleWorkerRegistration();
}

function scheduleWorkerRegistration() {
  if (typeof window === 'undefined') return;
  const start = () => registerWorker();
  if (document.readyState === 'complete') {
    start();
    return;
  }
  window.addEventListener('load', start, { once: true });
}

// A deploy landing while a tab is open does NOT surface itself: the browser
// only checks for a new worker on a navigation by default. Since this project
// deploys often, that would mean a tab quietly plays yesterday's build for
// hours. So we poll registration.update() — but ONLY while the tab is visible,
// and throttled to hourly. An update check that happens during a game could
// hand the page a fresh worker mid-round, which is exactly what the prompt
// model exists to avoid; a background tab is a safe moment (JS is throttled
// and the child cannot be interacting), so checks are deliberately skipped
// while hidden and run on return to the foreground.
const UPDATE_CHECK_INTERVAL_MS = 60 * 60 * 1000; // 1 hour

async function registerWorker() {
  try {
    const { registerSW } = await import('virtual:pwa-register');

    let updateTimer = null;
    let registration = null;
    let visibilityListenerAdded = false;

    const checkForUpdate = () => {
      // update() throws if called while a check is already in flight on some
      // browsers; a failed check is harmless (the next tick retries).
      registration?.update?.().catch(() => {});
    };

    // We register from here, not from a plugin-injected script
    // (injectRegister: null), so there is exactly one registration path.
    updateSW = registerSW({
      immediate: true,

      onRegisteredSW(_swUrl, reg) {
        registration = reg;
        if (!reg) return;

        if (updateTimer) clearInterval(updateTimer);
        updateTimer = setInterval(() => {
          // Hidden tab only — see the comment above.
          if (document.visibilityState === 'visible') checkForUpdate();
        }, UPDATE_CHECK_INTERVAL_MS);

        // Returning to the tab is the natural moment to check, and it is the
        // case the interval alone would miss (a tab left open and then
        // reopened). Cheap: registration.update() is a conditional GET of a
        // tiny file.
        //
        // Guarded: onRegisteredSW is called once per registerSW() today, but
        // this listener is added to `document` and would stack duplicates if
        // the callback ever fired twice. The flag makes that impossible.
        if (!visibilityListenerAdded) {
          visibilityListenerAdded = true;
          document.addEventListener('visibilitychange', () => {
            if (document.visibilityState === 'visible') checkForUpdate();
          });
        }
      },

      onNeedRefresh() {
        usePwaStore.getState().setNeedRefresh(true);
      },

      onOfflineReady() {
        usePwaStore.getState().setOfflineReady(true);
      },

      onRegisterError(error) {
        // Registration failing (locked-down school browser, unsupported
        // context) must never break the app — it just means no offline/install.
        console.warn('[pwa] service worker registration failed:', error);
      },
    });
  } catch (error) {
    console.warn('[pwa] service worker registration skipped:', error);
  }
}

// Activate the waiting worker and reload.
//
// updateSW(true) sends SKIP_WAITING to the waiting worker; the generated worker
// calls self.skipWaiting() on receipt (verified in the built sw.js), and the
// library reloads on the resulting `controlling` event — so we never call
// location.reload() ourselves (see the reload-loop warning in vite.config.js).
//
// The guard matters: this is reachable from both the update toast and the
// error boundary, and firing it twice in quick succession could race the
// reload. If there is nothing waiting yet (e.g. no worker registered at all),
// updateSW(true) is a safe no-op by the library's own design, so no reload
// happens and the button simply does nothing rather than reloading pointlessly.
let applyingUpdate = false;
export function applyUpdate() {
  if (!updateSW || applyingUpdate) return;
  applyingUpdate = true;
  updateSW(true);
}

// Trigger the saved install prompt. Returns 'accepted', 'dismissed', or null
// when there was no prompt to show.
export async function promptInstall() {
  const { installEvent } = usePwaStore.getState();
  if (!installEvent) return null;
  try {
    await installEvent.prompt();
    const choice = await installEvent.userChoice;
    // The event can only be used once, whatever the choice.
    if (choice?.outcome === 'accepted') {
      usePwaStore.getState().markInstalled();
    } else {
      usePwaStore.getState().setInstallEvent(null);
    }
    return choice?.outcome ?? null;
  } catch {
    usePwaStore.getState().setInstallEvent(null);
    return null;
  }
}
