// pwa.js
// One place for everything install/offline/update related, so the entry point
// (main.jsx) only has to call initPwa() and no component has to know how the
// service worker is registered.
//
// The service worker itself is generated by vite-plugin-pwa (see vite.config.js)
// and precaches ONLY the app shell. This module owns:
//   - registering it (via the virtual module, dynamically imported so the
//     workbox-window runtime is not part of the first-paint bundle),
//   - exposing "a new version is ready" so the UI can offer an explicit refresh
//     instead of the worker seizing control mid-lesson (registerType 'prompt'),
//   - tracking online/offline so the app can say so,
//   - capturing the install event so we can show our own install button
//     (iOS never fires it — see the hint in PwaBadges.jsx).
import { create } from 'zustand';

// Running as an installed app rather than a browser tab. Two checks because
// iOS Safari predates the display-mode media query and uses navigator.standalone
// instead.
function detectStandalone() {
  if (typeof window === 'undefined') return false;
  try {
    if (window.matchMedia?.('(display-mode: standalone)').matches) return true;
  } catch {
    /* media query unsupported — fall through */
  }
  return window.navigator?.standalone === true;
}

// iOS Safari never fires `beforeinstallprompt`, so the only way to add the app
// to the home screen there is the manual Share → Add to Home Screen flow. We
// detect iOS so we can show a hint in place of the button — but only while the
// app is NOT already installed.
function detectIosInstallable() {
  if (typeof navigator === 'undefined' || typeof window === 'undefined') {
    return false;
  }
  const ua = navigator.userAgent || '';
  // iPadOS 13+ reports a desktop "Macintosh" user agent, so a plain /iPad/
  // test misses modern iPads. The touch-points check separates a real iPad
  // from an actual Mac.
  const isIos =
    /iPad|iPhone|iPod/.test(ua) ||
    (ua.includes('Macintosh') && navigator.maxTouchPoints > 1);
  return isIos && !detectStandalone();
}

const initialOnline =
  typeof navigator === 'undefined' ? true : navigator.onLine !== false;

export const usePwaStore = create((set) => ({
  online: initialOnline,
  standalone: false,
  // iOS only: worth showing the "Add to Home Screen" hint.
  iosInstallable: false,
  // A new service worker is installed and waiting; offer a refresh.
  needRefresh: false,
  // The shell is now cached — the app can be opened offline. Shown once.
  offlineReady: false,
  // The deferred BeforeInstallPromptEvent (Chromium only). Not serialisable,
  // so it lives only in memory and is never persisted.
  installEvent: null,

  setOnline: (online) => set({ online }),
  setStandalone: (standalone) => set({ standalone }),
  setIosInstallable: (iosInstallable) => set({ iosInstallable }),
  setNeedRefresh: (needRefresh) => set({ needRefresh }),
  setOfflineReady: (offlineReady) => set({ offlineReady }),
  dismissOfflineReady: () => set({ offlineReady: false }),
  setInstallEvent: (installEvent) => set({ installEvent }),
}));

// The updater returned by registerSW. Kept at module scope so applyUpdate() can
// ask the SAME registration to activate its waiting worker — calling
// registerSW() again would create a second registration.
let updateSW = null;

// Register once per page load. Safe to call repeatedly.
let initialised = false;

export function initPwa() {
  if (typeof window === 'undefined' || initialised) return;
  initialised = true;

  const store = usePwaStore.getState();

  store.setStandalone(detectStandalone());
  store.setIosInstallable(detectIosInstallable());

  // --- online / offline -----------------------------------------------------
  // A school tablet loses wifi constantly; surfacing it explains the spinners.
  window.addEventListener('online', () => usePwaStore.getState().setOnline(true));
  window.addEventListener('offline', () => usePwaStore.getState().setOnline(false));

  // --- installed-app state can change while the page is open ---------------
  try {
    const mql = window.matchMedia('(display-mode: standalone)');
    const onChange = () => usePwaStore.getState().setStandalone(mql.matches);
    mql.addEventListener('change', onChange);
  } catch {
    /* older Safari: no addEventListener on MediaQueryList — ignore */
  }

  // --- install prompt (Chromium) -------------------------------------------
  window.addEventListener('beforeinstallprompt', (event) => {
    // Stop Chrome's mini-infobar so our own button is the only affordance.
    event.preventDefault();
    usePwaStore.getState().setInstallEvent(event);
  });

  window.addEventListener('appinstalled', () => {
    // Clear the saved prompt and mark standalone so the button disappears.
    usePwaStore.getState().setInstallEvent(null);
    usePwaStore.getState().setStandalone(true);
    usePwaStore.getState().setIosInstallable(false);
  });

  registerWorker();
}

// A deploy landing while a tab is open does NOT surface itself: the browser
// only checks for a new worker on a navigation by default. Since this project
// deploys often, that would mean a tab quietly plays yesterday's build for
// hours. So we poll registration.update() — but ONLY while the tab is visible,
// and throttled to hourly. An update check that happens during a game could
// hand the page a fresh worker mid-round, which is exactly what the prompt
// model exists to avoid; a background tab is a safe moment (JS is throttled
// and the child cannot be interacting), so checks are deliberately skipped
// while hidden and run on return to the foreground.
const UPDATE_CHECK_INTERVAL_MS = 60 * 60 * 1000; // 1 hour

async function registerWorker() {
  try {
    const { registerSW } = await import('virtual:pwa-register');

    let updateTimer = null;
    let registration = null;

    const checkForUpdate = () => {
      // update() throws if called while a check is already in flight on some
      // browsers; a failed check is harmless (the next tick retries).
      registration?.update?.().catch(() => {});
    };

    // We register from here, not from a plugin-injected script
    // (injectRegister: null), so there is exactly one registration path.
    updateSW = registerSW({
      immediate: true,

      onRegisteredSW(_swUrl, reg) {
        registration = reg;
        if (!reg) return;

        if (updateTimer) clearInterval(updateTimer);
        updateTimer = setInterval(() => {
          // Hidden tab only — see the comment above.
          if (document.visibilityState === 'visible') checkForUpdate();
        }, UPDATE_CHECK_INTERVAL_MS);

        // Returning to the tab is the natural moment to check, and it is the
        // case the interval alone would miss (a tab left open and then
        // reopened). Cheap: registration.update() is a conditional GET of a
        // tiny file.
        document.addEventListener('visibilitychange', () => {
          if (document.visibilityState === 'visible') checkForUpdate();
        });
      },

      onNeedRefresh() {
        usePwaStore.getState().setNeedRefresh(true);
      },

      onOfflineReady() {
        usePwaStore.getState().setOfflineReady(true);
      },

      onRegisterError(error) {
        // Registration failing (locked-down school browser, unsupported
        // context) must never break the app — it just means no offline/install.
        console.warn('[pwa] service worker registration failed:', error);
      },
    });
  } catch (error) {
    console.warn('[pwa] service worker registration skipped:', error);
  }
}

// Activate the waiting worker and reload.
//
// updateSW(true) sends SKIP_WAITING to the waiting worker; the generated worker
// calls self.skipWaiting() on receipt (verified in the built sw.js), and the
// library reloads on the resulting `controlling` event — so we never call
// location.reload() ourselves (see the reload-loop warning in vite.config.js).
//
// The guard matters: this is reachable from both the update toast and the
// error boundary, and firing it twice in quick succession could race the
// reload. If there is nothing waiting yet (e.g. no worker registered at all),
// updateSW(true) is a safe no-op by the library's own design, so no reload
// happens and the button simply does nothing rather than reloading pointlessly.
let applyingUpdate = false;
export function applyUpdate() {
  if (!updateSW || applyingUpdate) return;
  applyingUpdate = true;
  updateSW(true);
}

// Trigger the saved install prompt. Returns true if the install was accepted.
export async function promptInstall() {
  const { installEvent } = usePwaStore.getState();
  if (!installEvent) return false;
  try {
    await installEvent.prompt();
    const choice = await installEvent.userChoice;
    // The event can only be used once, whatever the choice.
    usePwaStore.getState().setInstallEvent(null);
    return choice?.outcome === 'accepted';
  } catch {
    usePwaStore.getState().setInstallEvent(null);
    return false;
  }
}
