/// <reference types="vite/client" />

// vite-plugin-pwa injects this virtual module at build time (and provides a
// no-op stub in dev). Declaring it here keeps editors/TS from flagging the
// dynamic import in src/pwa.js as an unresolved module. There is no runtime
// file behind it — it is generated by the plugin.
declare module 'virtual:pwa-register' {
  export interface RegisterSWOptions {
    immediate?: boolean;
    onNeedRefresh?: () => void;
    onOfflineReady?: () => void;
    onRegistered?: (registration: ServiceWorkerRegistration | undefined) => void;
    onRegisteredSW?: (
      swUrl: string,
      registration: ServiceWorkerRegistration | undefined
    ) => void;
    onRegisterError?: (error: unknown) => void;
  }

  // Returns an updater: call it with `true` to activate a waiting worker and
  // reload, or with no argument to run an on-demand update check.
  export function registerSW(options?: RegisterSWOptions): (reloadPage?: boolean) => Promise<void>;

  export function useRegisterSW(options?: RegisterSWOptions): {
    needRefresh: [boolean, (value: boolean) => void];
    offlineReady: [boolean, (value: boolean) => void];
    updateServiceWorker: (reloadPage?: boolean) => Promise<void>;
  };
}
